-- insert into Publishers (username, email, password) VALUES ("ubisoft", "ubisoft@ubisoft.com", "123456789");
-- insert into Publishers (username, email, password) VALUES ("activision", "activision@gmail.com", "987654321");
